### ISSUE TITLE
PA Review: Business Page

### ISSUE THREAD

**Issue by brtsai** [brtsai/food-help#3]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds
- [x] Users can add/own business pages
- [x] Users can view a business' page
- [x] A business page has a list of information for the business (ie. Name, Address, Hours of operation, price range, other info)
- [x] A business page has a static image of its location on a map
- [x] A business page has a trifold of images that enlarge when hovered over
- [x] A business page has a list of reviews and their ratings

**Comment by ajansel** [comment]
This is looking excellent! A few thoughts: 
- Using Google's api would be ideal for Lat/Lng so that the user doesn't have to enter it
- In the meantime, updating the default to Yelp HQs might be cool
- Adding categories works very smoothly, nicely done! I would suggest putting an enter icon or a plus sign, something to signify to the user that they can add more categories
- When we click on the user's username it should probably send them to a list of all of `their` businesses (will need this to complete MVP but you can come back to it when you have the index working after implementing search) 
  - As well as needing adequate seeding for the demo user so that once you implement their business show page there's meaningful seed data too
- We will also check in with Isak tomorrow to see whether he was expecting you to have an edit business page
- May also want to add hours of operation / additional info since Yelp doesn't ask for it by default
